# Generated by Django 6.0 on 2025-12-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
